[package]
name = "A1_snippets_external_command"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["blocking"] }
quick-xml = "0.24.0"
strong-xml = "0.6"
minidom = "0.16.0"